token = "MTE5MDAyMDI4MTgwMTEyMTg2Mg.GFACOP.jXhlVPl9paS99csSQDv33ibvlWeJvOEkmQM2YE"
# Yerak 1 token: NzU5MDI3MDU4NjEzMDI2ODI3.GEjfqF.eXerOszkEyt4a_3-xH-6mp1kinMlHKGhXn7SBo
# Yerak 2 token: NzU5MDI3MDU4NjEzMDI2ODI3.Gnuf9c.7dXxfWN6nYdZRO4vLAYMWRYxocNLSGvgaaioi8
# Yerak's Bot token: MTE5MDAyMDI4MTgwMTEyMTg2Mg.GFACOP.jXhlVPl9paS99csSQDv33ibvlWeJvOEkmQM2YE
# Vitor token: NjIxMzEyMTk1MzA4OTQ1NDQ5.Gz-_Cw.9FeR3dALIdYq4oFNqlOhLiVKkNiiYvqmHPlu6U
# Bancada token: NzYzMzg1NDQzODUyMDkxNDAz.GBqC2M.UmC--HOL1ShtZYxF7sKXViC9KidIVUba3gNCLI